### PR TITLE
docs: generate deno types

### PR DESCRIPTION
**Pull request by system32uwu**
This isn't documented (at least at plain sight), pretty useful to add it to the README IMO.

Sorry for it being so poorly written, I'm kind of in a hurry mkaing a prototype with this tech, feel free to modify it accordingly.

Thank you for you work guys.

### CODE REVIEW

**Comment by system32uwu** [comment]
I'm also getting this in the generated code: 
`Relative import path "edgedb/_src/reflection/index.ts" not prefixed with / or ./ or ../`

image

Quickly solved it by cloning this repository and updating the import references to "./edgedb/..."

**Comment by system32uwu** [comment]
Apparently just pointing every import to "./edgedb/mod.ts" works fine. I'm guessing that the code gen utility should make this imports point to the Deno Land url right?

**Comment by system32uwu** [comment]
Well just creating a deno.json in the root of your project with this content seems to work fine:

```json
{
  "imports": {
    "edgedb/": "https://deno.land/x/edgedb/",
    "edgedb": "https://deno.land/x/edgedb/mod.ts"
  }
}
```

Reading the Deno documentation this seems obvious, but adding it to the documentation will surely be useful for newcomers.

**Comment by scotttrinh** [comment]
@system32uwu Ahh, looks like we're already recommending using an `importMap` in the [Query Builder docs](https://www.edgedb.com/docs/clients/js/querybuilder#generate-the-query-builder), so if you can update your PR to match the recommendation there (`deno.json` linking to a separate `importMap.json` file) we can just merge this.

**Comment by system32uwu** [comment]
Huh I completely missed that, sure, I don't have access to a PC right now but will do tomorrow, thanks

**Review by scotttrinh — APPROVED** [review]
Thanks so much for your contribution!

**Pull request merged**
